markdown: kramdown
permalink: /:categories/:title.html
url: jxm080511321.github.io
lsi: false
#pygments: true
safe: true
#auto: false 
gems: [jekyll-paginate]
paginate: 8
paginate_path: "page:num"
baseurl: 

# presonal config
title: JxmBar Blog
description: JxmBar's Blog, powered by Jekyll...
# feed: http://www.winfirm.cn/atom.xml
author: 姜晓明
domain: jxm080511321.github.io
seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
